#!/usr/bin/env bash
# lib/config.sh - persistent installer configuration and deployment state.
# shellcheck shell=bash

# Default installation root. Overridable at install time and then persisted.
SO_DEFAULT_INSTALL_DIR="/opt/sentinel-ops"

# Derived paths, set by config_set_paths().
INSTALL_DIR=""
CONFIG_DIR=""
CONFIG_FILE=""
SUPABASE_DIR=""
APP_DIR=""
LOGFLARE_DIR=""
BACKUP_DIR=""
STATE_DIR=""
STATE_FILE=""
PHASE_DIR=""
LOG_DIR=""
RUNTIME_DIR=""

# Configuration values (defaults; overridden by installer.env).
APP_REPOSITORY="git@github.com:BrainStation-23/sentinel-ops.git"
APP_BRANCH="main"
DEPLOY_KEY=""
# Public endpoints. The defaults are the local ports the stack actually binds,
# so an install with no arguments produces a working deployment on this host.
# Pass real hostnames (or answer the prompts) when putting it behind a domain.
SUPABASE_PUBLIC_URL="http://localhost:8000"
API_EXTERNAL_URL="http://localhost:8000"
SITE_URL="http://localhost:3000"
APP_PORT="3000"
# Where the frontend's published port is bound. The reverse proxy is the
# operator's responsibility, so the default is loopback: a proxy on this host
# reaches it, the public internet does not. Set to 0.0.0.0 only if the proxy
# runs on a different machine.
APP_BIND="127.0.0.1"
APP_IMAGE_NAME="sentinel-ops"
APP_CONTAINER_NAME="sentinel-ops-frontend"
ENABLE_LOGFLARE="true"
# postgres | bigquery - see docs/LOGFLARE.md
LOGFLARE_BACKEND="postgres"
GOOGLE_PROJECT_ID=""
GOOGLE_PROJECT_NUMBER=""

# Establish every path from the installation root.
config_set_paths() {
    INSTALL_DIR="$(strip_trailing_slash "$1")"
    CONFIG_DIR="${INSTALL_DIR}/config"
    CONFIG_FILE="${CONFIG_DIR}/installer.env"
    SUPABASE_DIR="${INSTALL_DIR}/supabase"
    APP_DIR="${INSTALL_DIR}/app"
    LOGFLARE_DIR="${INSTALL_DIR}/logflare"
    BACKUP_DIR="${INSTALL_DIR}/backups"
    STATE_DIR="${INSTALL_DIR}/.state"
    STATE_FILE="${STATE_DIR}/state.env"
    PHASE_DIR="${STATE_DIR}/phases"
    LOG_DIR="${INSTALL_DIR}/logs"
    RUNTIME_DIR="${INSTALL_DIR}/runtime"
}

config_make_dirs() {
    mkdir -p "$CONFIG_DIR" "$BACKUP_DIR" "$STATE_DIR" "$PHASE_DIR" \
             "$LOG_DIR" "$RUNTIME_DIR" "$LOGFLARE_DIR"
    # Config and state hold URLs and deployment metadata; keep them private.
    chmod 750 "$CONFIG_DIR" "$STATE_DIR" "$BACKUP_DIR" 2>/dev/null || true
}

# True when a previous installation exists at this root.
installation_exists() {
    [[ -f "$CONFIG_FILE" ]]
}

# Load installer.env. Values are read key by key so that the file can never
# execute arbitrary shell.
config_load() {
    [[ -f "$CONFIG_FILE" ]] || return 1
    local key val
    for key in APP_REPOSITORY APP_BRANCH DEPLOY_KEY SUPABASE_PUBLIC_URL \
               API_EXTERNAL_URL SITE_URL APP_PORT APP_BIND APP_IMAGE_NAME \
               APP_CONTAINER_NAME ENABLE_LOGFLARE LOGFLARE_BACKEND \
               GOOGLE_PROJECT_ID GOOGLE_PROJECT_NUMBER; do
        val="$(env_get "$CONFIG_FILE" "$key" || true)"
        [[ -n "$val" ]] && printf -v "$key" '%s' "$val"
    done
    return 0
}

config_save() {
    config_make_dirs
    local tmp
    tmp="$(mktemp)"
    {
        printf '# Sentinel Ops installer configuration\n'
        printf '# Generated by sentinel-ops %s\n' "$SO_INSTALLER_VERSION"
        printf '# Edit with care: this file is read by every update run.\n\n'
        printf 'INSTALL_DIR=%s\n'           "$INSTALL_DIR"
        printf 'SUPABASE_DIR=%s\n'          "$SUPABASE_DIR"
        printf 'APP_DIR=%s\n'               "$APP_DIR"
        printf 'LOGFLARE_DIR=%s\n'          "$LOGFLARE_DIR"
        printf 'BACKUP_DIR=%s\n\n'          "$BACKUP_DIR"
        printf '# Application repository\n'
        printf 'APP_REPOSITORY=%s\n'        "$APP_REPOSITORY"
        printf 'APP_BRANCH=%s\n'            "$APP_BRANCH"
        printf 'DEPLOY_KEY=%s\n\n'          "$DEPLOY_KEY"
        printf '# Public endpoints\n'
        printf 'SUPABASE_PUBLIC_URL=%s\n'   "$SUPABASE_PUBLIC_URL"
        printf 'API_EXTERNAL_URL=%s\n'      "$API_EXTERNAL_URL"
        printf 'SITE_URL=%s\n\n'            "$SITE_URL"
        printf '# Frontend runtime. Point your own reverse proxy at\n'
        printf '# APP_BIND:APP_PORT, and at Supabase Kong for the API.\n'
        printf 'APP_PORT=%s\n'              "$APP_PORT"
        printf 'APP_BIND=%s\n'              "$APP_BIND"
        printf 'APP_IMAGE_NAME=%s\n'        "$APP_IMAGE_NAME"
        printf 'APP_CONTAINER_NAME=%s\n\n'  "$APP_CONTAINER_NAME"
        printf '# Analytics (Logflare) - see docs/LOGFLARE.md\n'
        printf 'ENABLE_LOGFLARE=%s\n'       "$ENABLE_LOGFLARE"
        printf 'LOGFLARE_BACKEND=%s\n'      "$LOGFLARE_BACKEND"
        printf 'GOOGLE_PROJECT_ID=%s\n'     "$GOOGLE_PROJECT_ID"
        printf 'GOOGLE_PROJECT_NUMBER=%s\n' "$GOOGLE_PROJECT_NUMBER"
    } >"$tmp"
    cat "$tmp" >"$CONFIG_FILE"
    rm -f "$tmp"
    chmod 640 "$CONFIG_FILE" 2>/dev/null || true
    log_debug "configuration written to ${CONFIG_FILE}"
}

# ---------------------------------------------------------------------------
# Deployment state
# ---------------------------------------------------------------------------

state_get() {
    local key="$1" fallback="${2:-}" val
    val="$(env_get "$STATE_FILE" "$key" 2>/dev/null || true)"
    if [[ -n "$val" ]]; then printf '%s' "$val"; else printf '%s' "$fallback"; fi
}

state_set() {
    mkdir -p "$STATE_DIR"
    [[ -f "$STATE_FILE" ]] || {
        printf '# Sentinel Ops deployment state - managed automatically.\n' >"$STATE_FILE"
        chmod 640 "$STATE_FILE" 2>/dev/null || true
    }
    env_set "$STATE_FILE" "$1" "$2"
}

state_touch_updated() {
    state_set UPDATED_AT "$(date -Is 2>/dev/null || date)"
}

# ---------------------------------------------------------------------------
# Phase markers - the basis of idempotent re-runs
#
# A completed phase drops a marker file. On a re-run the installer skips a
# phase whose marker exists, so a failure late in the process does not force
# Supabase to be reinstalled or secrets to be regenerated.
# ---------------------------------------------------------------------------

phase_done() {
    [[ -f "${PHASE_DIR}/$1" ]]
}

phase_mark() {
    mkdir -p "$PHASE_DIR"
    printf '%s\n' "$(date -Is 2>/dev/null || date)" >"${PHASE_DIR}/$1"
}

phase_clear() {
    rm -f "${PHASE_DIR}/$1"
}

# Run a phase once. If its marker exists the phase is skipped unless
# SO_FORCE_PHASES=true. Usage: phase_once <name> <description> <function>
phase_once() {
    local name="$1" desc="$2" fn="$3"
    if phase_done "$name" && [[ "${SO_FORCE_PHASES:-false}" != "true" ]]; then
        log_ok "${desc} (already completed, skipping)"
        return 0
    fi
    phase_begin "$desc"
    if "$fn"; then
        phase_mark "$name"
        phase_end
        return 0
    fi
    return 1
}
