#!/usr/bin/env bash
# lib/logflare.sh - Logflare deployment and the Supabase logging pipeline.
#
# Logflare is treated as a phase of its own. Recent Supabase releases ship an
# "analytics" service in their compose file; older ones do not. Both cases are
# handled here:
#
#   bundled    -> configure the existing analytics service and its vector feed
#   standalone -> deploy our own compose overlay next to the Supabase stack
#
# The Supabase-side settings this phase owns are documented in docs/LOGFLARE.md.
# shellcheck shell=bash

LOGFLARE_PORT="4000"
LOGFLARE_MODE=""   # bundled | standalone, set by logflare_detect_mode()

logflare_detect_mode() {
    if supabase_compose config --services 2>/dev/null | grep -qx "analytics"; then
        LOGFLARE_MODE="bundled"
    else
        LOGFLARE_MODE="standalone"
    fi
    log_debug "logflare mode: ${LOGFLARE_MODE}"
    printf '%s' "$LOGFLARE_MODE"
}

# ---------------------------------------------------------------------------
# Supabase-side configuration
#
# These are the variables that enable the logging pipeline. They live in
# supabase/.env and are read by both the analytics service and vector.
# ---------------------------------------------------------------------------
logflare_configure_supabase() {
    local env_file="${SUPABASE_DIR}/.env" pub priv

    pub="$(env_get "$env_file" LOGFLARE_PUBLIC_ACCESS_TOKEN || true)"
    priv="$(env_get "$env_file" LOGFLARE_PRIVATE_ACCESS_TOKEN || true)"
    [[ -n "$pub" ]]  || { pub="$(random_token 32)";  env_set "$env_file" LOGFLARE_PUBLIC_ACCESS_TOKEN "$pub"; }
    [[ -n "$priv" ]] || { priv="$(random_token 32)"; env_set "$env_file" LOGFLARE_PRIVATE_ACCESS_TOKEN "$priv"; }

    # vector mounts the Docker socket to collect container logs. The location
    # differs on systems using rootless Docker or Podman's compatibility shim.
    local sock="/var/run/docker.sock"
    [[ -S "$sock" ]] || sock="$(env_get "$env_file" DOCKER_SOCKET_LOCATION || printf '/var/run/docker.sock')"
    env_set "$env_file" DOCKER_SOCKET_LOCATION "$sock"

    # Single-tenant Supabase mode: Logflare skips account creation and serves
    # the Studio log views directly.
    env_set "$env_file" LOGFLARE_SINGLE_TENANT "true"
    env_set "$env_file" LOGFLARE_SUPABASE_MODE "true"

    chmod 600 "$env_file" 2>/dev/null || true
    log_ok "Supabase logging variables configured"
}

# ---------------------------------------------------------------------------
# Standalone deployment
# ---------------------------------------------------------------------------

logflare_compose_file() { printf '%s/docker-compose.yml' "$LOGFLARE_DIR"; }

logflare_compose() {
    ( cd "$LOGFLARE_DIR" && compose --env-file "${LOGFLARE_DIR}/.env" -f docker-compose.yml "$@" )
}

# Render the standalone overlay from the shipped template.
logflare_install_standalone() {
    local template="${SO_ASSETS_DIR}/logflare/docker-compose.yml"
    [[ -f "$template" ]] || { log_error "Missing Logflare template: ${template}"; return 1; }

    mkdir -p "$LOGFLARE_DIR"
    cp "$template" "$(logflare_compose_file)"

    local sb_env="${SUPABASE_DIR}/.env" env_file="${LOGFLARE_DIR}/.env"
    local pg_pass pg_db pg_user network

    pg_pass="$(env_get "$sb_env" POSTGRES_PASSWORD || true)"
    pg_user="$(env_get "$sb_env" POSTGRES_USER || printf 'postgres')"
    pg_db="$(env_get "$sb_env" POSTGRES_DB || printf 'postgres')"

    # Join the network the Supabase stack already created, so Logflare can
    # reach the database by service name and vector can reach Logflare.
    network="$(supabase_network_name)"

    : >"$env_file"
    {
        printf '# Logflare standalone deployment - generated by sentinel-ops\n'
        printf 'LOGFLARE_PORT=%s\n'                   "$LOGFLARE_PORT"
        printf 'LOGFLARE_SINGLE_TENANT=true\n'
        printf 'LOGFLARE_SUPABASE_MODE=true\n'
        printf 'LOGFLARE_PUBLIC_ACCESS_TOKEN=%s\n'    "$(env_get "$sb_env" LOGFLARE_PUBLIC_ACCESS_TOKEN)"
        printf 'LOGFLARE_PRIVATE_ACCESS_TOKEN=%s\n'   "$(env_get "$sb_env" LOGFLARE_PRIVATE_ACCESS_TOKEN)"
        printf 'LOGFLARE_DB_HOSTNAME=%s\n'            "$(supabase_db_service)"
        printf 'LOGFLARE_DB_PORT=5432\n'
        printf 'LOGFLARE_DB_DATABASE=%s\n'            "$pg_db"
        printf 'LOGFLARE_DB_USERNAME=%s\n'            "$pg_user"
        printf 'LOGFLARE_DB_PASSWORD=%s\n'            "$pg_pass"
        printf 'LOGFLARE_DB_SCHEMA=_analytics\n'
        printf 'LOGFLARE_SUPABASE_NETWORK=%s\n'       "$network"
        printf 'LOGFLARE_SECRET_KEY_BASE=%s\n'        "$(random_token 32)"
    } >>"$env_file"
    chmod 600 "$env_file" 2>/dev/null || true

    log_info "Starting standalone Logflare..."
    if ! run_logged "logflare up" bash -c \
        "cd '$LOGFLARE_DIR' && ${DOCKER_COMPOSE_CMD[*]} --env-file '${env_file}' -f docker-compose.yml up -d"; then
        return 1
    fi
    log_ok "Logflare container started"
    return 0
}

# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

logflare_install() {
    if [[ "$ENABLE_LOGFLARE" != "true" ]]; then
        log_info "Logflare is disabled in the configuration; skipping."
        return 0
    fi

    logflare_configure_supabase || return 1
    logflare_detect_mode >/dev/null

    if [[ "$LOGFLARE_MODE" == "bundled" ]]; then
        log_info "Supabase ships an analytics (Logflare) service; configuring it."
        # Re-create only the logging services so the new environment is picked
        # up without restarting the database.
        run_logged "start analytics" bash -c \
            "cd '$SUPABASE_DIR' && ${DOCKER_COMPOSE_CMD[*]} --env-file '${SUPABASE_DIR}/.env' -f docker-compose.yml up -d analytics vector" \
            || log_warn "Could not restart the analytics services individually."
    else
        log_info "No bundled analytics service; deploying Logflare separately."
        logflare_install_standalone || return 1
    fi

    state_set LOGFLARE_MODE "$LOGFLARE_MODE"
    return 0
}

logflare_check() {
    local code
    code="$(_http_code "http://localhost:${LOGFLARE_PORT}/health")"
    [[ "$code" == "200" ]] && return 0
    # Some builds answer only on the root path.
    code="$(_http_code "http://localhost:${LOGFLARE_PORT}/")"
    [[ "$code" =~ ^(200|302|401)$ ]]
}

logflare_running() {
    if [[ "$(state_get LOGFLARE_MODE bundled)" == "standalone" ]]; then
        [[ -f "$(logflare_compose_file)" ]] || return 1
        local cid
        cid="$(logflare_compose ps -q logflare 2>/dev/null | head -n1)"
        [[ -n "$cid" ]] && [[ "$(docker inspect -f '{{.State.Running}}' "$cid" 2>/dev/null)" == "true" ]]
    else
        supabase_service_running analytics
    fi
}

logflare_health_check() {
    [[ "$ENABLE_LOGFLARE" == "true" ]] || return 0
    log_info "Waiting for Logflare..."
    if wait_for 120 5 logflare_check; then
        log_ok "Logflare available"
        return 0
    fi
    if logflare_running; then
        log_warn "Logflare is running but did not answer its health endpoint."
        log_warn "Logs may be delayed. Check: sentinel-ops logs logflare"
        return 0
    fi
    log_error "Logflare failed health check"
    return 1
}
