#!/usr/bin/env bash
# lib/proxy.sh - optional Caddy edge proxy.
#
# Supabase already ships Kong as its API gateway, so this does not replace it.
# Caddy sits in front purely to terminate TLS and route the two public
# hostnames to the services that already exist:
#
#   app.example.com      -> sentinel-ops frontend container
#   supabase.example.com -> Supabase's Kong gateway
# shellcheck shell=bash

proxy_dir()          { printf '%s/caddy' "$RUNTIME_DIR"; }
proxy_compose_file() { printf '%s/docker-compose.yml' "$(proxy_dir)"; }
proxy_caddyfile()    { printf '%s/Caddyfile' "$(proxy_dir)"; }

# Automatic HTTPS needs a real, publicly resolvable hostname. Anything else
# (localhost, a bare IP, the placeholder domains) gets plain HTTP so the
# install does not stall on a doomed ACME challenge.
_proxy_tls_capable() {
    local host="$1"
    [[ -n "$host" ]] || return 1
    case "$host" in
        localhost|localhost:*|127.*|0.0.0.0|*.local|*.localhost) return 1 ;;
        *.example.com|example.com) return 1 ;;
    esac
    # A bare IPv4 address cannot get a public certificate.
    [[ "$host" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] && return 1
    [[ "$host" == *.* ]]
}

proxy_generate_caddyfile() {
    local dir app_host sb_host app_site sb_site
    dir="$(proxy_dir)"
    mkdir -p "$dir"

    app_host="$(url_host "$SITE_URL")"
    sb_host="$SUPABASE_PROXY_DOMAIN"
    [[ -n "$sb_host" ]] || sb_host="$(url_host "$SUPABASE_PUBLIC_URL")"

    if _proxy_tls_capable "$app_host"; then app_site="$app_host"; else app_site=":80"; fi
    if _proxy_tls_capable "$sb_host";  then sb_site="$sb_host";   else sb_site=""; fi

    {
        printf '# Generated by sentinel-ops - edits are overwritten on update.\n'
        if [[ -n "$ACME_EMAIL" ]]; then
            printf '{\n\temail %s\n}\n\n' "$ACME_EMAIL"
        fi

        printf '%s {\n' "$app_site"
        printf '\treverse_proxy %s:%s\n' "$APP_CONTAINER_NAME" "$APP_PORT"
        printf '\tencode gzip zstd\n'
        printf '}\n\n'

        if [[ -n "$sb_site" ]]; then
            printf '%s {\n' "$sb_site"
            printf '\treverse_proxy kong:8000\n'
            printf '\tencode gzip zstd\n'
            printf '}\n'
        else
            printf '# Supabase is not proxied: %s cannot be issued a public certificate.\n' "$sb_host"
            printf '# It remains reachable on the host at port %s.\n' "$(supabase_kong_port)"
        fi
    } >"$(proxy_caddyfile)"
}

proxy_install() {
    [[ "$ENABLE_CADDY" == "true" ]] || { log_info "Reverse proxy disabled; skipping."; return 0; }

    local dir network template
    dir="$(proxy_dir)"
    network="$(supabase_network_name)"
    template="${SO_ASSETS_DIR}/caddy/docker-compose.yml"
    [[ -f "$template" ]] || { log_error "Missing Caddy template: ${template}"; return 1; }

    mkdir -p "$dir"
    cp "$template" "$(proxy_compose_file)"
    proxy_generate_caddyfile

    printf 'SUPABASE_NETWORK=%s\n' "$network" >"${dir}/.env"

    log_info "Starting the Caddy reverse proxy..."
    if ! run_logged "caddy up" bash -c \
        "cd '$dir' && ${DOCKER_COMPOSE_CMD[*]} --env-file '${dir}/.env' -f docker-compose.yml up -d"; then
        log_warn "Caddy did not start. The application is still reachable on port ${APP_PORT}."
        return 0
    fi
    log_ok "Reverse proxy running"
    return 0
}

proxy_running() {
    [[ "$ENABLE_CADDY" == "true" ]] || return 1
    container_running "sentinel-ops-caddy"
}
